오픈베타 에러 수정
so-sim/front pull request #138
Opened 2023-06-30 14:57 UTC by jma1020

## 👀 개요

오픈베타 에러 수정

<br />

## 🧑‍💻 구현 디테일 및 화면

- UserModal nickname 15자 제한
- memo에 내용 없을 시 detaillist에 사유와 메모 구분점 제거
- 오타 수정
- 주간 필터링 텍스트 '임시' 대응 (1주,2주,3주 ~~)
- 금액 100만원 이상 추가 입력 제한 추가

<br />

## ✔️ 참고 사항 및 자료

2023-06-30 23:54 UTC, Jong1co requested changes
저부분만 수정하시고 병합 해주시면 감사하겠습니다 :)
고생하셨씁니다~~!

2023-06-30 23:54 UTC, Jong1co commented on src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
> +      if (Number(amount.replaceAll(',', '')) > 1000000) return state;
엇 이 로직 convertFromPriceFormat 함수 안에 있는데 지금 생각해보니까
저 함수 안에 금액 제한하는 로직이 있으면 안 되겠군요,,🥲

혹시 convertFromPriceFormat 안에 해당 로직 지워서 올려주실 수 있을까요??

2023-06-30 23:54 UTC, Jong1co commented on src/components/DetailFine/DetailList/index.tsx
<img width="1033" alt="image" src="https://github.com/so-sim/front/assets/95389265/61aeff78-16be-4be5-a668-286823e3aa38">

inline style 제거하고 font subhead_02로 넣어주세요 !

2023-07-01 02:05 UTC, jma1020 commented on src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
> +      if (Number(amount.replaceAll(',', '')) > 1000000) return state;
넵~ 혹시 
![image](https://github.com/so-sim/front/assets/45344418/0698f08d-38e0-4e47-bb5d-d837fcedb990)
이 부분은 어떤 상황을 예외처리 하신걸까요?!

2023-07-01 02:11 UTC, jma1020 commented on src/components/DetailFine/DetailList/index.tsx
감사합니다! 🥰

2023-07-01 02:12 UTC, merged

2023-07-01 07:46 UTC, Jong1co commented on src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
> +      if (Number(amount.replaceAll(',', '')) > 1000000) return state;
저 로직이 없으면 문자가 입력되었을 때 NaN이 나오더라구요 ㅎㅅㅎ